Integrated the expression language package and updated tests
php-etl/fast-map-config pull request #3
Opened 2021-05-21 15:08 UTC by sebprt

2021-05-26 08:59 UTC, clemzarch approved these changes

2021-05-27 07:31 UTC, gplanchat requested changes

2021-05-27 07:31 UTC, gplanchat commented on src/CompositeBuilder.php
> +    public function expression(string $outputPath, Expression $expression, array $additionalVariables = []): self
Est-ce que tu peux accepter `string|Expression` sur l'argument `$expression` ?

2021-05-27 07:31 UTC, gplanchat commented on src/CompositeBuilderInterface.php
> +    public function expression(string $outputPath, Expression $expression, array $additionalVariables = []): CompositeBuilderInterface;
Idem.
Est-ce que tu peux accepter `string|Expression` sur l'argument `$expression` ?

2021-05-27 07:31 UTC, gplanchat commented on tests/functional/ArrayBuilderTest.php
> +                ->expression('[price]', new Expression('price( input["price"]["value"], input["price"]["currency"] )'))
Est-ce que tu peux faire 2 tests : l'un avec un paramètre de type `string`, le deuxième avec un paramètre de type `Expression` ?

2021-05-28 07:55 UTC, sebprt commented on src/CompositeBuilder.php
> +    public function expression(string $outputPath, Expression $expression, array $additionalVariables = []): self
Fait

2021-05-31 08:10 UTC, sebprt commented on tests/functional/ArrayBuilderTest.php
> +                ->expression('[price]', new Expression('price( input["price"]["value"], input["price"]["currency"] )'))
Fait.

2021-05-31 14:22 UTC, clemzarch approved these changes

2021-06-02 07:37 UTC, gplanchat approved these changes

2021-06-03 09:09 UTC, merged